### ISSUE TITLE
Unable to install cotonti 0.9.20 on PHP less than 5.6 and Mysql less than 5.7

### ISSUE THREAD

**Issue by jameswill** [Cotonti/Cotonti#1658] opened 2022-08-16 10:11 UTC
Hi,

I tried installing cotonti 0.9.20 on PHP 5.5 and Mysql 5.5 However on starting the manual installation it gave the following error.

_**Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in [[PATH]]/system/database.php on line 567**_ 

So I increased the PHP to 5.6 and the above error disappeared leading to another following error on populating database on MYsql 5.5.

**_SQL error HY000: General error: 1709 Index column size too large. The maximum column size is 767 bytes._**

Is the script supported on these old versions of PHP and MYsql ?

**Comment by Alex300** [comment] 2022-08-17 06:47
MySQL fixed. Can be installed from the master branch. Checked MySQL 5.1 and higher.

With PHP is more difficult. Declaration of CotDB::query() is not compatible with PDO::query(). This is not allowed in new versions of PHP. Barbara Liskov substitution principle.
I used quick workaround, but it works only in PHP 5.6 and higher.
There is an another and more right way. Use composition instead of inheritance. And it will be implemented in nearest time. So minimal required PHP version will be 5.4

P.S. I had no idea that someone else was using such old software)))

P.P.S Someday we'll have to drop Legacy support anyway to move forward

- [ ] MySQL. Don't use 'utf8mb4' charset ot MySQL < 5.7 and/or PHP < 5.5
- [ ] PHP. Refactor CotDB class to use composition instead of inheritance from PDO. Also it is a first step to use different data bases, not only MySQL.

**Comment by webitproff** [comment] 2022-08-19 10:59
After making the last two edits and fixes
https://github.com/Cotonti/Cotonti/commit/0a250e62be9b26430d0e2f154b7ccfea8cf99710
https://github.com/Cotonti/Cotonti/commit/8ed43a4c93c9033a43fdc619c452d69cec3205cd
 - errors when exporting and importing a SQL v5.7 database via phpMyAdmin

**Comment by Alex300** [comment] 2022-08-22 05:51
I have it installed locally and it works fine on MySQL 5.7. But more testing is needed.
I don't use PhpMyAdmin so it's hard to say something for sure.
If it doesn't like the `'utf8mb4'` charset, you can still use `'utf8'`. To use it, before installing Cotonti, in the file `'datas/config-sample.php'` replace
```
$cfg['mysqlcharset'] = 'utf8mb4';
$cfg['mysqlcollate'] = 'utf8mb4_unicode_ci';
```
with
```
$cfg['mysqlcharset'] = 'utf8';
$cfg['mysqlcollate'] = 'utf8_unicode_ci';
```
The installer uses these options. In MySQL 8, utf8mb4 is the default encoding.

**Comment by seditio** [comment] 2022-08-22 06:13
> I have it installed locally and it works fine on MySQL 5.7. But more testing is needed.
Hi, what kind of testing is needed?

> I don't use PhpMyAdmin so it's hard to say something for sure. If it doesn't like the `'utf8mb4'` charset, you can still use `'utf8'`.
Just checked MySQL version info on some virtual hosting projects -- it is 5.5.xx-xx.x with `'utf8mb4'` charsets available.

Will test the package with both utf8 and utf8mb4 charsets and post feedback here.

**Comment by webitproff** [comment] 2022-08-23 10:17
complete nonsense! how to deal with it?
I was so embarrassed in front of the customer praising cotonti
http://youresite.com/admin/other
<img class="size-full wp-image-1310" src="http://freelance-script.abuyfile.com/wp-content/uploads/2022/08/Screenshot-2022-08-23-at-13-14-01-Прочее-Администрирование-Freelance-Marketplace.png" alt="Cotonti Siena v0.9.20.1 Последняя версия" width="630" height="355" />

**Comment by Alex300** [comment] 2022-08-23 14:27
Wrong descriptions are fixed in https://github.com/Cotonti/Cotonti/commit/23248dd1511ccb9dae959b55a200c7a1a392c99b

**Comment by webitproff** [comment] 2022-08-23 14:49
теперь порядок

**Comment by webitproff** [comment] 2022-08-23 14:51
now as intended! thanks a lot
<img class="size-full wp-image-1310" src="http://freelance-script.abuyfile.com/wp-content/uploads/2022/08/[Screenshot-2022-08-23-at-13-14-01-Прочее-Администрирование-Freelance-Marketplace.png](http://freelance-script.abuyfile.com/wp-content/uploads/2022/08/Screenshot-2022-08-23-at-17-46-51-Прочее-Администрирование-Freelance-Marketplace.png)" alt="Cotonti Siena v0.9.20.1 Последняя версия" width="" height="" />

**Comment by webitproff** [comment] 2022-08-23 15:01
if you are interested in the admin panel https://github.com/webitproff/cot-controlcot

**Comment by Alex300** [comment] 2022-08-24 06:25
It will be better if you add your theme here https://www.cotonti.com/themes/admin-panel/

**Comment by Alex300** [comment] 2022-08-25 14:22
CotDB class is refactored. If somebody can test it, please do it )))

**Closed** 2022-08-29 13:07 UTC
