### ISSUE TITLE
$cfg[maxrowsperpage] error

### ISSUE THREAD

**Issue by esclkm** [Cotonti/Cotonti#1447] opened 2015-11-12 17:27 UTC
$cfg[maxrowsperpage] error - cant edit a value of this param

**Comment by macik** [comment] 2015-11-17 18:03
It's a duplicate of https://github.com/Cotonti/Cotonti/issues/1368#issuecomment-129222559
So closing it now.

**Closed by macik** 2015-11-17 18:03 UTC
