### ISSUE TITLE
PM module  while replying to a message

### ISSUE THREAD

**Issue by Kabak** [Cotonti/Cotonti#1687] opened 2023-03-24 14:34 UTC
When you trying to reply  PM message once again you will saw not CKEditor block, but simple big editbox.  But in messages history displayed normal CKEditor block

Is it normal ?

Seems, CKEditor should be displayed also when you try to reply message.

**Comment by Alex300** [comment] 2023-03-25 08:45
I can't reproduce it. https://skr.sh/sJ1lgh7Ha5E?a Can you please provide more info how to get it?

**Comment by Kabak** [comment] 2023-03-25 13:20
Try to reply on already replied message [https://i.gyazo.com/8dd0df838f90e8932e04db1fb26b009b.png](url)
and you will get this [https://i.gyazo.com/6f06121f33a36db9d74f974daa0b28d2.png](url)

**Comment by Alex300** [comment] 2023-03-25 15:51
It appears when Ajax is enabled in the module settings. It would be nice to describe such details. Well, or apply screenshots with urls)

Fixed with https://github.com/Cotonti/Cotonti/commit/4b7534da2eff7c191388ae590931f9b25973d4c3. You can update the module and check.

**Closed** 2023-03-25 15:52 UTC
Labels: Extension related, Bug

**Comment by Kabak** [comment] 2023-03-26 02:28
It does not fixed

I updated the files from fix, and message Icon has bad redirection : **index.php?e=pm#get;e=pm&m=message&id=2**

should be  **index.php?e=pm&m=message&id=2**
