### ISSUE TITLE
HTTPS related inconsistencies

### ISSUE THREAD

**Issue by macik** [Cotonti/Cotonti#1543] opened 2016-10-29 21:36 UTC
There are several faults: 
1. Site scheme ignored on install:  while installing on HTTPS site, we get HTTP scheme in `$cfg['mainurl']` after install.
2. We get unpredictable behavior on some certain configuration of HTTP servers while serving HTTPS connection. Spotted at least on Reverse proxy configs where we get 80 exposed in URL in some cases.
   See [this topic](https://www.cotonti.com/forums?m=posts&q=8097) ( :ru: ).

**Comment by Viste** [comment] 2018-02-22 10:05
any news?

**Comment by Viste** [comment] 2018-03-20 11:21
почти 2 года на исправление хака, которого в принципе быть не должно....  Мощь!

**Comment by Viste** [comment] 2018-04-26 12:32
Вхуярьте, что-то типа If ($_SERVER['SERVER_PORT'] != 80) {
            $http_host= str_replace(':' . $_SERVER['SERVER_PORT'], '', $http_host);

**Comment by Alex300** [comment] 2021-09-07 15:22
1) Fixed with f51e40e5d1e1285d83c923ff8a506c6d8b7ddf57
2) Can't reproduce

**Closed** 2022-06-09 14:38 UTC
Labels: bug
