### ISSUE TITLE
Official site down

### ISSUE THREAD

**Issue by PSalador** [Cotonti/Cotonti#1585] opened 2017-11-12 14:41 UTC
http://www.cotonti.com/ is inaccessible.

**Comment by CrazyFreeMan** [comment] 2017-11-12 18:39
game over

**Comment by Kilandor** [comment] 2017-11-12 18:50
I have alerted Trustmaster to the issue, it should be resolved soon. The problem is it is not redirecting to https. For now you can just use https://www.cotonti.com

**Comment by seditio** [comment] 2017-11-13 07:37
Problem is that I can only access cotonti.com via proxy from Russia (sometimes), US (sometimes), NL or France. Guess most of the Russian-speaking audience too.

**Comment by PSalador** [comment] 2017-11-13 08:42
Yes, I access to site via Tor Browser.

**Comment by macik** [comment] 2017-11-14 07:46
As for now investigation is in progress. Checking DNS as it experiencing some kind of DDoS.

**Comment by macik** [comment] 2017-12-06 16:46
Please check site access once more.

**Comment by PSalador** [comment] 2017-12-06 16:49
Yes, everything works.

**Comment by yusupovb** [comment] 2017-12-26 11:13
Dnserror! Site available only with proxy.

**Comment by macik** [comment] 2017-12-29 06:55
Yes. DNS has some problems.

As quick workaround (work me) — set Google DNS for my Network connection:
 for IPv4 service:
```
8.8.8.8
8.8.4.4
```
and for IPv6 access 
```
2001:4860:4860::8888
2001:4860:4860::8844
```

**Comment by Roffun** [comment] 2019-04-13 20:08
This problem has something to do with the Cotonti branch ?

**Comment by Kilandor** [comment] 2019-04-14 05:55
Just closing this is old. It doesn't need to be open.

**Closed by Kilandor** 2019-04-14 05:55 UTC
Labels: bug, critical
